### ISSUE TITLE
Try loosening the version requirement for beautifulsoup

### ISSUE THREAD

**Issue by yuanxu-li** [yuanxu-li/html-table-extractor#18]
The version of beautifulsoup4 is pinned to 4.5.3.

The original motivation is that when I was developing this library, 4.5.3 worked, and I didn't want to come across any unintended behavior of other versions.

Considering that this library is being used by other projects that depend on other versions of beautifulsoup4, to loosen the version requirement would make it easier for this library to be adopted by other projects.

**Comment by fjsj** [comment]
@yuanxu-li I guess this isn't properly solved because on `setup.py` on `install_requires` there's a hard `'beautifulsoup4==4.5.3'`

**Comment by yuanxu-li** [comment]
@fjsj Good catch! Fixed it in `setup.py`!
