### ISSUE TITLE
python3 compat

### ISSUE THREAD

**Issue by hampsterx** [yuanxu-li/html-table-extractor#2]
```
print ext.return_list()
```
heh

**Comment by yuanxu-li** [comment]
This part https://github.com/yuanxu-li/html-table-extractor/blob/master/html_table_extractor/extractor.py#L113 was for testing purpose. I think I will remove it.

I will try the whole thing on python3. It should be fine since I do not use any python2-specific features.

**Comment by yuanxu-li** [comment]
@hampsterx closed by 7baebf8cec40ba58d071884a21f421fd62c3ef02

**Comment by yuanxu-li** [comment]
@hampsterx closed by 7baebf8cec40ba58d071884a21f421fd62c3ef02
