### ISSUE TITLE
Make new release

### ISSUE THREAD

**Issue by isaacto** [yuanxu-li/html-table-extractor#20]
The current version, 1.4.0, still have the beautifulsoup4==4.5.3 dependency.  Unluckily, beautifulsoup4 really needs to be upgraded, because the previous version [uses features deprecated in Python 3.7](https://bugs.launchpad.net/beautifulsoup/+bug/1778909) and removed in Python 3.8. I noticed that the setup.py is already modified to take the new >=4 version tag in master, so a simple release of the current code should be sufficient to fix the issue.

**Comment by vjer** [comment]
@yuanxu-li I remember asking for that change to the version requirement! Would love to get a release that has it since we're running into the same problem isaacto is. :)

**Comment by joshuatbadger** [comment]
Same here, running into this issue.

**Comment by isaacto** [comment]
If you hit the problem and want temporary relief, you can use my temporary re-release at https://pypi.org/project/isaacto-html-table-extractor/ .

**Comment by yuanxu-li** [comment]
Thank you for raising the issue :)

I just released the new version 1.4.1.

**Comment by vjer** [comment]
Thank you!
